version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/" # Location of Dockerfile
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget" # Added for csproj packages
    directory: "/" # Typically the directory containing the .csproj files
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "some-specific-dependency" # Example of ignoring a specific dependency
    commit-message:
      prefix: "fix" # Optional prefix for commit message
